### ISSUE TITLE
Social ghost isn't working // instagram stories

### ISSUE THREAD

**Issue by Doener350** [nhymxu/social-ghost-ext#12]
In Instagram stories you will be marked as seen and the story does not refresh wehen you refresh the page

**Comment by dwiyatci** [comment]
I was gonna report about this, too. 😃 @nhymxu https://github.com/nhymxu/social-ghost-ext/pull/13 looks good to me - could you please approve it and publish a new version? 🙏

**Comment by nhymxu** [comment]
Merged. will submit new version soon.
Manually because I'm not finish CI/CD yet 🥲
