### ISSUE TITLE
Social ghost isn't working.

### ISSUE THREAD

**Issue by sociagen** [nhymxu/social-ghost-ext#2]
Tips? Fix?

It was really useful, thank you.

**Comment by nhymxu** [comment]
@sociagen 

Hi, can you provide more information?
I'm testing again with Facebook stories and still work

**Comment by nhymxu** [comment]
Look like instagram change the way app work. I'll investigate on it

**Comment by nhymxu** [comment]
@sociagen submit new fix version.
I'm waiting firefox review new version
